### ISSUE TITLE
Display math is not centered

### ISSUE THREAD

**Issue by PatrickMassot** [pkra/mathjax-node-page#18]
I'm still trying to replace the deprecated page2svg by mjpage. Test document:
```html
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
</head>
<body>
	\[
	a + b = x
	\]
</body>
</html>
```
The math is converted to svg but it is not horizontally centered  and has no extra vertical margin.

**Comment by pkra** [comment]
> I'm still trying to replace the deprecated page2svg by mjpage.

Thanks! I appreciate it.

> The math is converted to svg but it is not horizontally centered and has no extra vertical margin.

Thanks for catching that. There's not actually an API in mathjax-node for getting those styles. I'll file a bug upstream to check if we want to add one.

**Comment by pkra** [comment]
Cf. https://github.com/mathjax/MathJax-node/issues/283

**Comment by pkra** [comment]
For the record, below is the slimmed down CSS that mathjax-node used to add:

```css
.MathJax_SVG_Display {
    text-align: center;
    margin: 1em 0em;
    position: relative;
    display: block!important;
    text-indent: 0;
    max-width: none;
    max-height: none;
    min-width: 0;
    min-height: 0;
    width: 100%
}

.MathJax_SVG .MJX-monospace {
    font-family: monospace
}

.MathJax_SVG .MJX-sans-serif {
    font-family: sans-serif
}

.MathJax_SVG {
    display: inline;
    font-style: normal;
    font-weight: normal;
    line-height: normal;
    font-size: 100%;
    font-size-adjust: none;
    text-indent: 0;
    text-align: left;
    text-transform: none;
    letter-spacing: normal;
    word-spacing: normal;
    word-wrap: normal;
    white-space: nowrap;
    float: none;
    direction: ltr;
    max-width: none;
    max-height: none;
    min-width: 0;
    min-height: 0;
    border: 0;
    padding: 0;
    margin: 0
}

.MathJax_SVG * {
    transition: none;
    -webkit-transition: none;
    -moz-transition: none;
    -ms-transition: none;
    -o-transition: none
}

.mjx-svg-href {
    fill: blue;
    stroke: blue
}

.MathJax_SVG_LineBox {
    display: table!important
}

.MathJax_SVG_LineBox span {
    display: table-cell!important;
    width: 10000em!important;
    min-width: 0;
    max-width: none;
    padding: 0;
    border: 0;
    margin: 0
}
```
